/* Static catalogue data for the Turismo Inteligente frontend. */
const visitorData = [
            { id: "VIS-8801", origin: "Bogotá - Chapinero", destination: "PNN El Cocuy", transport: "Vehículo", time: "09:12 AM", status: "Activo" },
            { id: "VIS-8802", origin: "Medellín - El Poblado", destination: "Piedra del Peñol - Guatapé", transport: "Autobús", time: "09:08 AM", status: "Activo" },
            { id: "VIS-8803", origin: "Manizales - Centro", destination: "PNN Los Nevados (Ruiz)", transport: "Vehículo", time: "08:55 AM", status: "Inactivo" },
            { id: "VIS-8804", origin: "Tunja - Norte", destination: "Laguna de Tota", transport: "Autobús", time: "08:42 AM", status: "Activo" }
        ];

const touristPlaces = [
            { id: 1, name: "Parque Nacional Natural El Cocuy", lat: 6.4000, lng: -72.3000, desc: "La masa glaciar más grande de Colombia con más de 25 picos nevados.", category: "Aventura", img: "https://upload.wikimedia.org/wikipedia/commons/e/e3/PNN_El_Cocuy.jpg", busInfo: "Buses a El Cocuy (~$70.000 COP)", funFact: "Posee la masa continua de nieve e hielo más grande de los Andes septentrionales." },
            { id: 2, name: "Parque Nacional Natural Los Nevados (Ruiz)", lat: 4.8920, lng: -75.3188, desc: "Estratovolcán nevado y ecosistemas de páramo.", category: "Naturaleza", img: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Nevado_del_Ruiz_volcano.jpg", busInfo: "Tours autorizados desde Manizales", funFact: "Sus frailejones crecen solo 1 cm por año." },
            { id: 3, name: "Laguna de Tota", lat: 5.5458, lng: -72.9213, desc: "El lago más grande de Colombia con su famosa Playa Blanca a 3.015 msnm.", category: "Naturaleza", img: "https://upload.wikimedia.org/wikipedia/commons/d/da/Laguna_de_tota-_Boyac%C3%A1_Colombia.jpg", busInfo: "Buses desde Sogamoso (~$8.000 COP)", funFact: "Alberga la playa de agua dulce a mayor altitud de América del Sur." },
            { id: 4, name: "Rocas de Suesca", lat: 5.1053, lng: -73.8011, desc: "Escalada deportiva y farallones rocosos icónicos.", category: "Aventura", img: "https://upload.wikimedia.org/wikipedia/commons/2/23/Rocas_de_Suesca.JPG", busInfo: "Flotas desde Portal Norte (~$12.000 COP)", funFact: "Es considerada la cuna de la escalada en roca en Colombia." },
            { id: 5, name: "Piedra del Peñol - Guatapé", lat: 6.2200, lng: -75.1798, desc: "Monolito gigante de 220 metros con vista panorámica a un embalse.", category: "Aventura", img: "https://upload.wikimedia.org/wikipedia/commons/5/53/El_Pe%C3%B1ol_Guatape_Colombia.jpg", busInfo: "Buses desde la Terminal del Norte de Medellín", funFact: "Tiene 740 escalones incrustados en su grieta principal." },
            { id: 6, name: "Cabo de la Vela", lat: 12.2071, lng: -72.1802, desc: "Encuentro mágico entre el desierto wayúu y el Mar Caribe.", category: "Naturaleza", img: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Cabo_de_la_Vela%2C_La_Guajira.jpg", busInfo: "Camionetas 4x4 desde Uribia", funFact: "Territorio sagrado donde viajan las almas de los Wayúu." },
            { id: 7, name: "Nuquí - Chocó", lat: 5.7095, lng: -77.2667, desc: "Avistamiento de ballenas jorobadas y selva tropical.", category: "Naturaleza", img: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Nuqu%C3%AD_Choc%C3%B3_Colombia.jpg", busInfo: "Vuelo Charter desde Medellín", funFact: "Recibe a miles de ballenas jorobadas de la Antártida." },
            { id: 8, name: "Caño Cristales - Meta", lat: 2.2472, lng: -73.7847, desc: "El río de los cinco colores o el río más hermoso del mundo.", category: "Aventura", img: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Cano_Cristales_Macarena_Colombia.jpg", busInfo: "Vuelo a La Macarena + Canoa por el río", funFact: "Sus colores son producidos por la planta Macarenia clavigera." },
            { id: 9, name: "Puerto Nariño - Amazonas", lat: -3.7799, lng: -70.3640, desc: "Poblado ecológico en el Amazonas y delfines rosados.", category: "Naturaleza", img: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Puerto_Nari%C3%B1o_Amazonas.jpg", busInfo: "Lancha rápida desde Leticia", funFact: "Municipio 100% peatonal sin vehículos a motor." },
            { id: 10, name: "Piedra Colgada de Susa", lat: 5.4521, lng: -73.8114, desc: "Formación rocosa y mirador sobre el valle de Ubaté.", category: "Aventura", img: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Susa_Cundinamarca.jpg", busInfo: "Buses hacia Ubaté / Susa", funFact: "Da la ilusión óptica de estar flotando en el aire." },
            { id: 11, name: "Laguna de la Cocha (Pasto)", lat: 1.1550, lng: -77.1500, desc: "Embalse natural de origen glaciar con casitas de estilo suizo.", category: "Naturaleza", img: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Laguna_de_la_Cocha_-_Nari%C3%B1o.jpg", busInfo: "Colectivo desde Pasto hasta El Encano", funFact: "Alberga el Santuario de Flora Isla La Corota." },
            { id: 12, name: "Catedral de Sal Zipaquirá", lat: 5.0189, lng: -74.0044, desc: "Santuario subterráneo esculpido en sal.", category: "Cultural", img: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Zipaquira_Salt_Cathedral_2016.jpg", busInfo: "Buses intermunicipales desde Portal Norte", funFact: "Primera Maravilla de Colombia a 180 metros bajo tierra." },
            { id: 13, name: "Laguna de Guatavita", lat: 4.9786, lng: -73.7744, desc: "Cuna sagrada de la Leyenda de El Dorado.", category: "Naturaleza", img: "https://upload.wikimedia.org/wikipedia/commons/8/86/Laguna_Guatavita_1.JPG", busInfo: "Flotas Valle de Tenza / Guatavita", funFact: "Sitio del ritual del Zipa Muisca bañado en oro." },
            { id: 14, name: "Cerro de Monserrate", lat: 4.6058, lng: -74.0555, desc: "Santuario y mirador panorámico sobre Bogotá.", category: "Histórico", img: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Monserrate_Bogota.jpg", busInfo: "TransMilenio Estación Las Aguas", funFact: "Ubicado a 3.152 msnm sobre la capital." },
            { id: 15, name: "Ciudad Amurallada Cartagena", lat: 10.4236, lng: -75.5512, desc: "Patrimonio histórico con arquitectura colonial.", category: "Histórico", img: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Cartagena_de_Indias_-_Ciudad_Amurallada.jpg", busInfo: "Vía terrestre / Avión", funFact: "Murallas construidas durante más de 200 años." },
            { id: 16, name: "Parque Nacional Tayrona", lat: 11.3000, lng: -74.0500, desc: "Encuentro entre la Sierra Nevada y el Mar Caribe.", category: "Naturaleza", img: "https://upload.wikimedia.org/wikipedia/commons/3/36/Playa_Cabo_San_Juan_-_Tayrona.jpg", busInfo: "Buses desde Santa Marta hacia El Zaino", funFact: "Unión directa de la Sierra Nevada con el mar." }
        ];
